In [20]:
import pandas as pd
import os

os.chdir("C:\\Users\\admin\\SM-RuleMiner")
print(os.getcwd())

C:\Users\admin\SM-RuleMiner

In [69]:
df = pd.read_csv("diabetes.csv")
col = df.columns.tolist()
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [62]:
df.head(10)
drop_ind = [i for i in range(0,10,2)]
print(drop_ind)
df.drop(drop_ind,axis = 0,inplace =True)
df.reset_index(drop = True)
df.head(10)

[0, 2, 4, 6, 8]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
9,8,125,96,0,0,0.0,0.232,54,1
11,10,168,74,0,0,38.0,0.537,34,1
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
19,1,115,70,30,96,34.6,0.529,32,1
22,7,196,90,0,0,39.8,0.451,41,1
23,9,119,80,35,0,29.0,0.263,29,1

In [64]:
def makeMonkey(args):
    monkey = {}
    
    i = 0
    
    for j in range(0,len(args),3):
        monkey[i] = args[j:j+3]
        i += 1
    
    return monkey

def read_rule(rule):
    rule = makeMonkey(rule)
    print("\nIf ")
    for k,v in rule.items():
        if v[0] == 1:
            mx = max(v[1],v[2])
            mn = min(v[1],v[2])
            print(f"{mn} <= {col[k]} <= {mx} and ")
    print("Then Class = Positive\n")


def delRows(args,sign):
    if(df.shape[0] < 50):
        print("Data set size less then threshold\n")
        return
    
    drop_ind = []
    args = makeMonkey(args)
    score = 0
    index = df.index.tolist()
    for i in index:
        rule_satisfied = True
        for k,v in args.items():
            if v[0] == 1:
                mn = min(v[1],v[2])
                mx = max(v[1],v[2])

                if df.iloc[i][col[k]] < mn or df.iloc[i][col[k]] > mx:
                    rule_satisfied = False
                    break
        if rule_satisfied and df.iloc[i]["Outcome"] == sign:
            score += 1
            drop_ind.append(i)

    df.drop(drop_ind,axis = 0,inplace = True)
    return score

In [51]:
args = [
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,19.27,96.28,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.36,2.0,1,23,74],
    [0,0,0,1,95,179,0,0,0,0,0,0,0,0,0,1,31.7,58.16,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,1,32,95,0,0,0,0,0,0,0,0,0,0,0,0]
]

In [65]:
for i in range(0,len(args)):
    print(df.index.tolist())
    print(f"Size : {df.shape[0]}\n")
    read_rule(args[i])
    score = delRows(args[i],0)
    print(f"Score : {score}\n")

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767]
Size : 768


If
19.27 <= BMI <= 96.28 and
Then Class = Positive

Score : 486

[0, 2, 4, 6, 8, 9, 11, 13, 14, 15, 16, 17, 19, 22, 23, 24, 25, 26, 31, 37, 38, 39, 43, 45, 48, 49, 53, 56, 60, 61, 64, 66, 70, 72, 78, 81, 84, 88, 90, 93, 99, 100, 109, 110, 111, 114, 115, 116, 120, 124, 125, 128, 129, 130, 131, 132, 143, 145, 152, 154, 155, 159, 164, 165, 170, 171, 175, 177, 179, 185, 186, 187, 188, 189, 192, 193, 195, 197, 198, 199, 206, 207, 209, 213, 214, 215, 216, 218, 219, 220, 221, 227, 230, 231, 235, 236, 237, 238, 239, 242, 243, 245, 254, 255, 259, 261, 264, 266, 269, 270, 276, 280, 283, 284, 287, 291, 292, 293, 296, 298, 300, 301, 303, 306, 308, 309, 312, 314, 317, 319, 321, 322, 323, 326, 328, 332, 337, 338, 339, 349, 355, 356, 357, 359, 360, 363, 366, 369, 370, 371, 375, 378, 386, 387, 388, 391, 394, 397, 399, 400, 402, 404, 406, 408, 409, 414, 415, 417, 418, 419, 424, 425, 426, 427, 429, 435, 438, 440, 443, 444, 445, 448, 451, 455, 458, 468, 476, 480, 484, 485, 493, 494, 498, 502, 506, 510, 515, 516, 522, 523, 526, 535, 539, 540, 541, 542, 545, 546, 560, 561, 569, 577, 579, 580, 584, 586, 588, 590, 592, 595, 598, 603, 604, 606, 611, 612, 614, 618, 619, 630, 635, 638, 642, 646, 647, 648, 655, 659, 661, 662, 663, 664, 666, 667, 675, 676, 678, 681, 683, 684, 689, 691, 693, 695, 696, 701, 702, 706, 708, 709, 712, 715, 716, 719, 722, 730, 731, 732, 739, 740, 743, 746, 748, 749, 750, 753, 754, 755, 757, 759, 761, 766]
Size : 282


If
0.36 <= DiabetesPedigreeFunction <= 2.0 and
23 <= Age <= 74 and
Then Class = Positive

IndexError: single positional indexer is out-of-bounds